#let STAMM = "München"
#let PLZ = "81739 München"
#let ADDRESS = "Maximilian-Kolbe-Allee 18"
#let GROUPTIME = "Freitag, 16.00-18.00 Uhr"
#let SFM = "Vroni Spörl"
#let MAIL = "stammstjakobus@gmail.com"
#let PHONE = "01577774472"
#let INSTAGRAM = "@muenchen"
#let WICHTEL = false
#let twoWEEKS = false
#let STAMMESMEISTERIN = true
#let WOLF_PHOTO = "pictures/Wölflinge.jpeg"
#let WOLF_X = 0mm
#let WOLF_Y = 0mm
#let WOLF_Z = 1
#let PFADI_PHOTO = "pictures/Pfadfinder.png"
#let PFX = 0mm
#let PFY = 0mm
#let PFZ = 1
#let RAIDER_PHOTO = "pictures/Raider2.jpg"
#let RAX = -62mm
#let RAY = 2mm
#let RAZ = 1.1
